version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

    # Add reviewer
    reviewers:
      - "anelson"

    # Pull request settings
    pull-request-branch-name:
      separator: "-"

    # Version update settings
    versioning-strategy: "auto"

    # Commit message settings
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
