include = ["**/*.toml"]

[formatting]
allowed_blank_lines = 2
column_width        = 80

align_entries        = true
array_auto_collapse  = true
array_auto_expand    = true
array_trailing_comma = true
reorder_keys         = true
trailing_newline     = true

crlf                = false
inline_table_expand = false
