# cargo release config specifically for `sssstar` crate

[[pre-release-replacements]]
file    = "../README.md"
replace = "ssstar = \"{{version}}\""
search  = "ssstar = \"[\\d\\.]+\""
# Don't do this replacement when the version is a development version
prerelease = false
